# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.14/slk_0.1.14_Darwin_x86_64.tar.gz"
      sha256 "da9d6e560a2ee23bb95e8cfd31ad281331e4696e05f26b32afaefaf0a8db83f5"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.14/slk_0.1.14_Darwin_arm64.tar.gz"
      sha256 "bf7b56d0b1953232839f3c25abd7a2cc94ce09042ecce1bfba5aa0488501a322"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.14/slk_0.1.14_Linux_x86_64.tar.gz"
      sha256 "ef10f42246f08617353c3d6f4a9b99047ae5b7fdc1de7b64c4c7ab7841d9863c"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.14/slk_0.1.14_Linux_arm64.tar.gz"
      sha256 "4c2f322bf56ea309ef430b4ccf3702fb375354ce8110a43d2acd9f6940b5c323"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end
end
