# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Slack for Non-Humans™ - Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.3.0/slk_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "a37476b274b4e78360052a972dbd3f2b33db599821d8226932e0e2f8807024b3"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.3.0/slk_0.3.0_Darwin_arm64.tar.gz"
      sha256 "38c9a75550c79690cca504ac653d81f4056d47e9162dbed3e6a8b911e78cbfce"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.3.0/slk_0.3.0_Linux_x86_64.tar.gz"
      sha256 "c4d14c7fa8f485d60cdc268df2e8dd2342a0c32ba025de45dae64aec6fc313f4"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.3.0/slk_0.3.0_Linux_arm64.tar.gz"
      sha256 "1f30f53a9c1afe7f38c42f5189890e98de40bc6de1ffbf0bfeace29888238634"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end
end
