# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Slack for Non-Humans™ - Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.5.0/slk_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "ca208ac3ab313163f27dad93b93fc3130f912539a6e0ac80d7592e4ceec075e4"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.5.0/slk_0.5.0_Darwin_arm64.tar.gz"
      sha256 "f5122840e4dc34055806d029fd1ff6d239822434b122a74ea5388ca3de2d2641"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.5.0/slk_0.5.0_Linux_x86_64.tar.gz"
      sha256 "b715ecb0cae54ac25b21d958c4c5bee5b8042084fa4da7f3ea7366572201217a"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.5.0/slk_0.5.0_Linux_arm64.tar.gz"
      sha256 "dc18b9ad68751cc5724225bf46a3b5c3f8bfabe80e37b302c747b8861fd7312c"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end
end
